### ISSUE TITLE
Request: incorporate salvage from turrets

### ISSUE THREAD

**Issue by EricAKAPode** [mcb5637/BTSimpleMechAssembly#2]
Denadan's(?) Custom Salvage is based on Salvage Operations, but he expanded it to have turrets drop salvage 30% of the time also. With how potent some of the heavy and modded turrets are, I felt this was important and have been using CS in BEXCE instead of SO. I've watched your progress and really prefer what you've done design wise as well as bugfixing. Any chance you could crib the turret code from CS and make the ultimate salvage mod?

**Comment by mcb5637** [comment]
I have looked for a list of all dead Turrets before, but didn't find one. If i find one, i might add it for the next version.

**Comment by EricAKAPode** [comment]
I'm not sure how Denadan did it but he'd probably help if you asked on the RT modding discord

**Comment by mcb5637** [comment]
still in testing, but 382033ff811a088042e5dcba612ff0fac61c8200 seems to do what we want

**Comment by mcb5637** [comment]
done
